languageCode = "en-us"
title = "Ardi Mirzaei"
baseurl = "ardimirzaei.github.io"
theme = "aerial"

[params]
  name = "Ardi Mirzaei"
  about = "Pharmacist - Researcher - Educator - Data Scientist"
  copyright = "2020 Ardi Mirzaei "
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"
  plugins_css = "custom"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/ArdiMirzaei"

[[params.social]]
  medium = "Google"
  icon = "google"
  link = "https://scholar.google.com.au/citations?user=I7_fS5sAAAAJ&hl=en"

[[params.social]]
  medium = "University Profile"
  icon = "university"
  link = "https://sydney.edu.au/medicine-health/about/our-people/academic-staff/ardalan-mirzaei.html"

[[params.social]]
  medium = "ORCiD"
  icon = "opera"
  link = "https://orcid.org/0000-0002-1398-0648"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/ardimirzaei"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/ardimirzaei"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:ardalan.mirzaei@sydney.edu.au"

  publishDir ="/"
