baseURL = "ardimirzaei.github.io"
languageCode = "en"
defaultContentLanguage = "en"
title = "Ardi Mirzaei"
theme = "stip"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Ardi Mirzaei"
    bio = "Pharmacist - Researcher - Educator - Data Scientist"

[params]


    [[params.links]]
      medium = "LinkedIn"
      icon = "linkedin"
      link = "https://www.linkedin.com/in/ArdiMirzaei"

    [[params.links]]
      medium = "Google"
      icon = "google"
      link = "https://scholar.google.com.au/citations?user=I7_fS5sAAAAJ&hl=en"

    [[params.links]]
      medium = "University Profile"
      iconset = "fas"
      icon = "university"
      link = "https://sydney.edu.au/medicine-health/about/our-people/academic-staff/ardalan-mirzaei.html"

    [[params.links]]
      medium = "ORCiD"
      icon = "fa-orcid"
      link = "https://orcid.org/0000-0002-1398-0648"

    [[params.links]]
      medium = "Twitter"
      icon = "twitter"
      link = "https://twitter.com/ardimirzaei"

    [[params.links]]
      medium = "Github"
      icon = "github"
      link = "https://github.com/ardimirzaei"

    [[params.links]]
      medium = "Email"
      iconset = "fas"
      icon = "envelope"
      link = "mailto:ardalan.mirzaei@sydney.edu.au"
      